# Generated by Django 4.0.3 on 2022-07-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('asume_cargo', models.DateField()),
                ('deja_cargo', models.DateField()),
                ('cartera', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fundacion', models.DateField()),
                ('antiguedad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('asume_cargo', models.DateField()),
                ('deja_cargo', models.DateField()),
                ('partido', models.CharField(max_length=60)),
                ('constitucional', models.BooleanField()),
            ],
        ),
    ]
