# Generated by Django 4.0.3 on 2022-07-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
